import { StyleSheet } from "react-native";

// Light theme palette (Clean Light).
export const colors = {
  bg: "#f7f8fa",
  surface: "#ffffff",
  surfaceAlt: "#f1f3f6",
  border: "#e3e6ea",
  borderSoft: "#eef0f3",
  textPrimary: "#1a1d21",
  textSecondary: "#5b626c",
  textMuted: "#8a909a",
  accent: "#3a6ff7",
  accentSoft: "#e6eefe",
  brand: "#3a6ff7",
  green: "#16a34a",
  red: "#dc2626",
  amber: "#d97706",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    padding: 20,
    gap: 14,
  },
  errorText: {
    color: colors.red,
    fontWeight: "600",
  },
  infoText: {
    color: colors.accent,
    fontWeight: "600",
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  subTitle: {
    marginTop: 6,
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceAlt,
  },
  button: {
    backgroundColor: colors.brand,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  memberName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  memberMeta: {
    marginTop: 2,
    color: colors.textSecondary,
  },
  inviteRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  clubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  clubRowLogo: {
    width: 36,
    height: 36,
    borderRadius: 9,
    marginRight: 10,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  clubRowLogoImage: {
    width: 36,
    height: 36,
  },
  clubRowLogoText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 14,
  },
  clubRowText: {
    flex: 1,
    paddingRight: 8,
  },
  clubChevron: {
    fontSize: 26,
    color: colors.accent,
    fontWeight: "700",
  },
  contactsCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  contactRow: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    paddingVertical: 8,
  },
  rowActions: {
    marginTop: 8,
    gap: 8,
  },
  separator: {
    height: 1,
    backgroundColor: colors.borderSoft,
  },
  paid: {
    color: colors.green,
    fontWeight: "600",
  },
  unpaid: {
    color: colors.red,
    fontWeight: "600",
  },
  warn: {
    color: colors.amber,
    fontWeight: "600",
  },
  muted: {
    color: colors.textSecondary,
    fontWeight: "600",
  },
  dueRowText: {
    flex: 1,
    paddingRight: 8,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricCard: {
    width: "48%",
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  metricValue: {
    marginTop: 4,
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  metaText: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  segmentRow: {
    flexDirection: "row",
    gap: 8,
  },
  segment: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  segmentActive: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  segmentText: {
    color: colors.textSecondary,
    fontWeight: "600",
  },
  segmentTextActive: {
    color: "#ffffff",
    fontWeight: "700",
  },
  segmentBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentBadgeText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "700",
  },
  noticeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 12,
    gap: 4,
  },
  noticeUnreadCol: {
    width: 16,
    paddingTop: 6,
    alignItems: "center",
  },
  noticeTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  noticeSubject: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: "500",
  },
  noticeSubjectUnread: {
    fontWeight: "800",
  },
  noticeSender: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 1,
  },
  noticePreview: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  noticeDate: {
    fontSize: 12,
    color: colors.textMuted,
  },
  noticeDetailSubject: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.textPrimary,
    marginBottom: 6,
  },
  noticeDetailMeta: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 12,
  },
  noticeDetailBody: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.textPrimary,
    marginTop: 12,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  inlineButton: {
    backgroundColor: colors.accentSoft,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  inlineButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontWeight: "600",
    fontSize: 13,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  // --- 3-tab shell: club header ---
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.bg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerClub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 40,
    height: 40,
  },
  avatarText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  headerClubName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  headerRole: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 1,
  },
  headerChevron: {
    fontSize: 18,
    color: colors.textSecondary,
    marginLeft: 4,
  },
  headerBell: {
    fontSize: 20,
    color: colors.textSecondary,
  },
  // --- 3-tab shell: club switch sheet ---
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    paddingBottom: 40,
    gap: 12,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: colors.border,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
  },
  switchRowActive: {
    borderWidth: 2,
    borderColor: colors.accent,
  },
  switchCheck: {
    fontSize: 18,
    color: colors.accent,
    fontWeight: "700",
  },
  // --- role badges (generic) ---
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: colors.surfaceAlt,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  // --- setup tab rows ---
  setupRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  setupRowLabel: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: "500",
  },
  setupRowMeta: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  // --- members directory (mockup) ---
  directoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  directoryTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  inviteLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  inviteLinkText: {
    color: colors.accent,
    fontWeight: "600",
    fontSize: 14,
  },
  directoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  memberAvatarImage: {
    width: 40,
    height: 40,
  },
  memberAvatarText: {
    color: colors.textSecondary,
    fontWeight: "700",
    fontSize: 13,
  },
  directoryNameCol: {
    flex: 1,
    gap: 2,
  },
  directoryName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  directoryMeta: {
    fontSize: 13,
    color: colors.textMuted,
  },
  roleChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  roleChipText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.textSecondary,
  },
  shareCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 18,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
  },
  shareQr: {
    width: 34,
    height: 34,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  shareQrGlyph: {
    fontSize: 26,
    color: colors.textSecondary,
  },
  shareTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  shareLink: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  shareCopy: {
    fontSize: 20,
    color: colors.accent,
  },
  // --- invite bottom sheet (contact picker) ---
  inviteSheetSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: -6,
  },
  inviteSearch: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.textPrimary,
    fontSize: 14,
  },
  contactPickRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
  },
  contactCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  contactCheckboxOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  contactCheckboxTick: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  contactPickName: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  contactPickPhone: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 1,
  },
  contactStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  contactStatusPillText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  inviteSheetFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
    marginTop: 4,
  },
  inviteSheetCount: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  inviteSendBtn: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  inviteSendBtnDisabled: {
    borderColor: colors.border,
  },
  inviteSendBtnText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
  inviteSendBtnTextDisabled: {
    color: colors.textMuted,
  },
  inviteSheetAltLink: {
    alignSelf: "center",
    paddingVertical: 6,
  },
  inviteSheetAltLinkText: {
    color: colors.accent,
    fontSize: 13,
  },
  inviteEmptyState: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 24,
  },
  inviteEmptyIcon: {
    fontSize: 40,
  },
  inviteEmptyHeading: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  inviteEmptyBody: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 19,
  },
  inviteSheetPrimaryBtn: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    alignSelf: "stretch",
  },
  inviteSheetPrimaryBtnText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
  inviteSheetGhostBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    alignSelf: "stretch",
  },
  inviteSheetGhostBtnText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  shareQrLarge: {
    width: 180,
    height: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  shareQrLargeGlyph: {
    fontSize: 120,
    color: colors.textPrimary,
  },
  shareLinkCentered: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
  },
  // --- members empty-state invite surface ---
  inviteSurface: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    gap: 10,
  },
  // --- setup tab sheets ---
  sheetLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: -4,
  },
  emailStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    marginTop: -2,
  },
  emailStatusVerified: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.green,
  },
  emailStatusPending: {
    fontSize: 13,
    color: colors.textMuted,
    flexShrink: 1,
  },
  emailStatusAction: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.accent,
  },
  sheetMemberRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    gap: 8,
  },
  rolePillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  rolePill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  rolePillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  rolePillText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  rolePillTextActive: {
    color: colors.accent,
    fontWeight: "600",
  },
  dangerButton: {
    borderWidth: 1,
    borderColor: colors.red,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  dangerButtonText: {
    color: colors.red,
    fontSize: 15,
    fontWeight: "600",
  },
  // --- Activity tab ---
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 6,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  pollOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 8,
    overflow: "hidden",
  },
  pollOptionActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  pollOptionFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.surfaceAlt,
  },
  pollOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pollOptionLabel: {
    color: colors.textPrimary,
    fontWeight: "600",
    flexShrink: 1,
    paddingRight: 8,
  },
  pollOptionCount: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  toastHost: {
    position: "absolute",
    left: 16,
    right: 16,
    alignItems: "center",
  },
  toast: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    maxWidth: 520,
    width: "100%",
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderLeftWidth: 4,
    paddingVertical: 12,
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  toastIcon: {
    fontSize: 15,
    fontWeight: "700",
  },
  toastText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  authSafe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  authScroll: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  authLogoWrap: {
    alignItems: "center",
    marginBottom: 36,
  },
  authCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 22,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  authHeading: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  authSubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: -6,
    lineHeight: 20,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: -4,
  },
  authFooter: {
    textAlign: "center",
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 24,
    lineHeight: 18,
  },
  avatarPicker: {
    alignSelf: "center",
    alignItems: "center",
    gap: 6,
  },
  avatarPickerCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarPickerImage: {
    width: 88,
    height: 88,
  },
  avatarPickerGlyph: {
    fontSize: 30,
    color: colors.textMuted,
  },
  avatarPickerHint: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.accent,
  },
  consentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  consentBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  consentBoxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  consentTick: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  consentText: {
    flex: 1,
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  consentLink: {
    color: colors.accent,
    fontWeight: "600",
  },
});
