import { StyleSheet } from "react-native";

// Dark theme palette (matches the Members mockup).
export const colors = {
  bg: "#0f1113",
  surface: "#16181c",
  surfaceAlt: "#1b1e23",
  border: "#26292e",
  borderSoft: "#1f2227",
  textPrimary: "#f2f4f7",
  textSecondary: "#9aa1ab",
  textMuted: "#6b7280",
  accent: "#4d8bf5",
  accentSoft: "#1e2a44",
  brand: "#3a6ff7",
  green: "#34d399",
  red: "#f87171",
  amber: "#fbbf24",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    padding: 20,
    gap: 14,
  },
  stepText: {
    fontSize: 13,
    color: colors.accent,
    fontWeight: "600",
  },
  errorText: {
    color: colors.red,
    fontWeight: "600",
  },
  infoText: {
    color: colors.accent,
    fontWeight: "600",
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: -6,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  subTitle: {
    marginTop: 6,
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceAlt,
  },
  button: {
    backgroundColor: colors.brand,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  memberName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  memberMeta: {
    marginTop: 2,
    color: colors.textSecondary,
  },
  inviteRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  clubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  clubRowText: {
    flex: 1,
    paddingRight: 8,
  },
  clubChevron: {
    fontSize: 26,
    color: colors.accent,
    fontWeight: "700",
  },
  contactsCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  contactRow: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
    paddingVertical: 8,
  },
  rowActions: {
    marginTop: 8,
    gap: 8,
  },
  separator: {
    height: 1,
    backgroundColor: colors.borderSoft,
  },
  paid: {
    color: colors.green,
    fontWeight: "600",
  },
  unpaid: {
    color: colors.red,
    fontWeight: "600",
  },
  warn: {
    color: colors.amber,
    fontWeight: "600",
  },
  muted: {
    color: colors.textSecondary,
    fontWeight: "600",
  },
  dueRowText: {
    flex: 1,
    paddingRight: 8,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricCard: {
    width: "48%",
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  metricValue: {
    marginTop: 4,
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  metaText: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  segmentRow: {
    flexDirection: "row",
    gap: 8,
  },
  segment: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  segmentActive: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  segmentText: {
    color: colors.textSecondary,
    fontWeight: "600",
  },
  segmentTextActive: {
    color: "#ffffff",
    fontWeight: "700",
  },
  inlineButton: {
    backgroundColor: colors.accentSoft,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  inlineButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontWeight: "600",
    fontSize: 13,
  },
  // --- 3-tab shell: club header ---
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.bg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerClub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  headerClubName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  headerRole: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 1,
  },
  headerChevron: {
    fontSize: 18,
    color: colors.textSecondary,
    marginLeft: 4,
  },
  headerBell: {
    fontSize: 20,
    color: colors.textSecondary,
  },
  // --- 3-tab shell: club switch sheet ---
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    gap: 12,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: colors.border,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
  },
  switchRowActive: {
    borderWidth: 2,
    borderColor: colors.accent,
  },
  switchCheck: {
    fontSize: 18,
    color: colors.accent,
    fontWeight: "700",
  },
  // --- role badges (generic) ---
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: colors.surfaceAlt,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  // --- setup tab rows ---
  setupRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  setupRowLabel: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: "500",
  },
  setupRowMeta: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  // --- members directory (mockup) ---
  directoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  directoryTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  inviteLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  inviteLinkText: {
    color: colors.accent,
    fontWeight: "600",
    fontSize: 14,
  },
  directoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAvatarText: {
    color: colors.textSecondary,
    fontWeight: "700",
    fontSize: 13,
  },
  directoryName: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  roleChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  roleChipText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.textSecondary,
  },
  shareCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 18,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
  },
  shareQr: {
    width: 34,
    height: 34,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  shareQrGlyph: {
    fontSize: 26,
    color: colors.textSecondary,
  },
  shareTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  shareLink: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  shareCopy: {
    fontSize: 20,
    color: colors.accent,
  },
  // --- invite bottom sheet (contact picker) ---
  inviteSheetSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: -6,
  },
  inviteSearch: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.textPrimary,
    fontSize: 14,
  },
  contactPickRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
  },
  contactCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  contactCheckboxOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  contactCheckboxTick: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  contactPickName: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  contactPickPhone: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 1,
  },
  contactStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  contactStatusPillText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  inviteSheetFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
    marginTop: 4,
  },
  inviteSheetCount: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  inviteSendBtn: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  inviteSendBtnDisabled: {
    borderColor: colors.border,
  },
  inviteSendBtnText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
  inviteSendBtnTextDisabled: {
    color: colors.textMuted,
  },
  inviteSheetAltLink: {
    alignSelf: "center",
    paddingVertical: 6,
  },
  inviteSheetAltLinkText: {
    color: colors.accent,
    fontSize: 13,
  },
  inviteEmptyState: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 24,
  },
  inviteEmptyIcon: {
    fontSize: 40,
  },
  inviteEmptyHeading: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  inviteEmptyBody: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 19,
  },
  inviteSheetPrimaryBtn: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    alignSelf: "stretch",
  },
  inviteSheetPrimaryBtnText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
  inviteSheetGhostBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    alignSelf: "stretch",
  },
  inviteSheetGhostBtnText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  shareQrLarge: {
    width: 180,
    height: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  shareQrLargeGlyph: {
    fontSize: 120,
    color: colors.textPrimary,
  },
  shareLinkCentered: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
  },
  // --- members empty-state invite surface ---
  inviteSurface: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    gap: 10,
  },
});
